prediction_location_rename_dict ={
    "Arenum": "Arenum Bergen",
    "Åsane Kirke Bergen": "Åsane kirke, Bergen",
    "Bergenshus Festning, Bergen": "Bergenhus Festning",
    "Forum Scene, Foajéen": "Forum Scene",
    "Bergen Kunsthall": "Kunsthall",
    "Madam Felle, Bergen": "Madam Felle",
    "Norges Handelshøyskole, Bergen": "Norges Handelshøyskoles",
    "Nykirken, Bergen": "Nykirken",
    "Ricks Teater": "Ricks Theatre",
    "Cementen": "Cementen, Stavanger",
    "Clarion Hotel Stavanger": "Clarion Hotel Energy",
    "Folken,Stavanger": "Folken, Løkkeveien",
    "BLÅ Brenneriveien 9c 0182 Oslo": "Brenneriveien, Oslo",
    "Cosmopolite": "Cosmopolite, Oslo",
    "HERR NILSEN, OSLO": "Herr Nilsen",
    "Latter": "Latter, Oslo",
    "Parkteatret Scene, Oslo": "Parkteatret Scene",
    "ROCKEFELLER": "Rockefeller",
    "Tøyen": "Tøyenparken",
    "Ullevaal Stadion, Oslo": "Ulleval",
    "Ullevaal Stadium": "Ulleval",
    "Universitetets Aula, Oslo": "University of Oslo",
    "Byscenen, Trondheim": "Byscenen",
    "Dokkhuset": "Dokkhuset Scene",
    "Dahls Arena": "EC Dahls Arena",
    "Lerkendal Stadion, Trondheim": "Lerkendal stadion",
    "NIDAROS DOMKIRKE": "Nidaros Cathedral",
    "Rock City, Trondheim": "Rockheim",
    "Rosendal Teater, Trondheim": "Rosendal Theatre",
    "Trøndelag Teater-Teaterkjelleren": "Trøndelag Theatre",
    "Trøndelag Teater, Hovedscenen": "Trøndelag Theatre",
    "Trøndelag Teater, Studioscenen": "Trøndelag Theatre",
    "Vår Frue Kirke Trondheim": "Vår Frue Kirke",
    "SALT, Langhuset": "Salt Langhuset",
}